services:
  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joseluis
      MYSQL_DATABASE: escolar
      MYSQL_USER: luis
      MYSQL_PASSWORD: joseluis
    ports:
        - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command : --bind-address=0.0.0.0
    networks:
        - mysql_network      
volumes:
   mysql_data:
    driver: local
networks:
  mysql_network:
    driver: bridge